# 1. Imagen base
FROM php:8.2-apache

# 2. Copiamos los archivos
COPY . /var/www/html/

# 3. Exponemos el puerto
EXPOSE 80

# 4. Metadatos (MAINTAINER está obsoleto, se usa LABEL)
LABEL maintainer="JL Gonzalez <jlgs@cifpvirgendegracia.com>"